version: "2"

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - "27017:27017"
    volumes:
      - giftr-db:/data/db
    restart: always
    command: mongod

  web:
    image: ikeybenz/giftr:latest
    env_file: .env
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo


volumes:
  giftr-db: